### ISSUE TITLE
Namelist for the idealised galaxy disc

### ISSUE THREAD

**Issue by marionfarcy** [blaizot/ramses-tutorials#12]
There are a number of parameters that have a different value in the nml for the idealised disc without RT and with RT activated, which are the following: levelmax, n_star, eps_star, eta_sn. Even IG_rho and IG_T2 from the DICE_PARAMS section are different. Which values should we use?

**Comment by marionfarcy** [comment]
Also, I think it is better to turn sink=.false. in both namelist, and only turn it to true together with clumpfind when activating BH accretion and AGN feedback.

**Comment by marionfarcy** [comment]
We need to provide a SED to the GitHub repository, and update the path in the nml?

More generally, we could remove parameters whose values are the same as the default in RAMSES, and focus only on what needs to be changed for a specific run (e.g. RT_GROUPS is not needed and kappaAbs is never used, "yield" is given but not used until the code is compiled with one extra variable... it might be misleading)

**Comment by marionfarcy** [comment]
Don't we need to set create_sinks to true for the run with BH and AGN feedback? Or is there already a BH in the ICs?

**Comment by mtrebitsch** [comment]
Working on it! For now my idea is to bypass SMBH seeding (because it's kind of iffy for idealised galaxy setups), but instead add a BH "by hand". I don't think it's well documented ( :roll_eyes: work for the doc WG I guess), but you can create a `ic_sink` file that needs to be put with the ICs. I'll write something up if we want to go this way.

One issue is that it significantly impacts the timestep (by a factor ~10 at least), at least in my tests with AGN feedback. It requires more careful testing etc, but I'm not surprised: there is hot gas, so high sound speed, so small timestep.

So before I go much further: do we want to explore this?

**Comment by marionfarcy** [comment]
Hi Maxime, all,

There is already a bunch of parameters associated with BH formation, growth and feedback in the nml given in this tutorial. When I run these, the outputs contain clump_snapnum.txtsnapnum and sink_snapnum.csv files, but I do not know if it means that a BH actually forms.

If we want to keep the section about BHs, we should probably make sure that a SMBH forms, and maybe simply add a few lines of codes explaining how to check this, and how to plot some BH-related property? Would this be feasible without investing too much time? I guess it is ok if the simulation takes longer to run, we could maybe just warn the user to stop the run after a few snapshots.

All the best,
Marion

On 18 Sep 2024, at 08:14, Maxime Trebitsch ***@***.***> wrote:



Working on it! For now my idea is to bypass SMBH seeding (because it's kind of iffy for idealised galaxy setups), but instead add a BH "by hand". I don't think it's well documented ( 🙄 work for the doc WG I guess), but you can create a ic_sink file that needs to be put with the ICs. I'll write something up if we want to go this way.

One issue is that it significantly impacts the timestep (by a factor ~10 at least), at least in my tests with AGN feedback. It requires more careful testing etc, but I'm not surprised: there is hot gas, so high sound speed, so small timestep.

So before I go much further: do we want to explore this?

**Comment by mtrebitsch** [comment]
Hi Marion,

* As far as I can tell, the clump and sink files are generated irrespective of whether sinks are actually formed. In my very initial tests I didn't get a sink, but I can test it further. One way to check is to look at the `header` files: if the number of cloud particles is 0, then no sinks are formed, if it is 2109, then you have one sink.
* But more generally, I'm a bit uncomfortable with seeding BH with clumps in idealised discs: I have no good feeling for where the sink will form (if it does), and depending on the noise in the ICs it might not always be "at the centre". Putting the sink "by hand" feels a bit more consistent with the "idealised" setup: you can decide to have an over-/under-massive BH pretty easily, and you can always put it at the centre of the box.
A second issue with the "clumpfinder" approach is that the tutorials will not (I think) cover the clumpfinder module, which is more versatile than just BH seeding (it can be used to literally track gas clumps for example), but IMO this goes beyond the scope of the tutorial.
* For the run time, I've managed to keep the timestep semi-decent ("only" a factor 10 slow-down) by using only "quasar-mode" feedback (i.e., setting `AGN_fbk_mode_switch_threshold=0d0`). This means that while there is hot gas, there is no strong momentum injection, which behaves a bit better. This still feels a bit too slow, as it would take more than 15 minutes (on my laptop) to reach the 2nd output. This is mostly due to the AGN having an initial accretion burst, which leads to a feedback burst, which kills the timestep.
I can find ways to go around this: for instance, only seeding the BH in the 2nd output, when things are a bit relaxed, so there should not be such a strong initial burst of activity, but maybe this goes a bit beyond what we want here. That being said, it might lead to an interesting discussion on "how fickle idealised ICs can be".
* For the BH-related properties, what did you have in mind? Unless we start with a severely under-massive BH and force-feed it, I do not expect the BH to grow significantly (since typically, the galaxy mass doesn't change much and BH models tend to lead to a coevolution between BH and stellar mass). We can still look at the "accreted mass", but this would require several outputs, which can take some time to get.

Finally, word of caution: I'm not super used to "this" AGN implementation in RAMSES (this is the Biernacki & Teyssier overhaul of the older Dubois et al implementation), so I might be missing some stuff.

**Comment by jokirosdahl** [comment]
> There are a number of parameters that have a different value in the nml for the idealised disc without RT and with RT activated, which are the following: levelmax, n_star, eps_star, eta_sn. Even IG_rho and IG_T2 from the DICE_PARAMS section are different. Which values should we use?

I changed the rho and T2 parameters in the RHD run to match those in the HD one. The levelmin and levelmax parameters had already been changed by someone.

**Comment by jokirosdahl** [comment]
> Also, I think it is better to turn sink=.false. in both namelist, and only turn it to true together with clumpfind when activating BH accretion and AGN feedback.

I agree, and I see you already committed it 👍

**Comment by jokirosdahl** [comment]
> @marionfarcy and I converged on the Idealised simulation tutorial. It's your turn now.
> 
> @jokirosdahl : we set sf params, but we left the different IG_rho and IG_T2 in the two namelist, please pick one. It would also be nice if you could plot something related to RT. @mtrebitsch : please check AGNs/sinks in the idealised galaxy setup + add a nice related plot.
> 
> Things left to do for anyone:
> 
> * Run the code to the end and make new plots.
> * Check the total computing time for the different runs.
> * For the section on star formation and the `m_star` parameter (step 3): check the minimal stellar mass of the stellar particles in the default run, and set a value for `m_star` that makes it change in the namelist example.

For plotting something related to the RT. You can already see it in the movies, and I think it's enough.
