### ISSUE TITLE
annotate_streamlines fails 

### ISSUE THREAD

**Issue by blaizot** [blaizot/ramses-tutorials#5]
In the tutorial Cosmological Volume, the display of the gravitational potential map does not work very well. The line "q1.annotate_strealines(...)" plainly crashes for me. 

Some discussion of what we see would be nice as well (what stands out in the potential map are the voids, i guess, which is perhaps counterintuitive ?).

**Comment by cspotz** [comment]
managed to get this on my laptop, I let you cross check it and place it in a new section or where it should be
![coucou](https://github.com/user-attachments/assets/18841554-9c4e-40c1-9622-8a410715a11e)
I added some words on voids, maybe simpler to say it orally also during the course

**Comment by blaizot** [comment]
This does not seem to work, does it ? The streamlines neatly ignore the halo ... 
If you can make it work, let me know.

**Comment by mtrebitsch** [comment]
I am not sure that this is an error, actually. I played around a bit and I think it's because the halo itself is moving across the box. One solution to isolate the "converging flows" around the halo would be to create a derived field of "velocity - halo velocity", and use that.

See below my tests:
- I created a spherical region to make sure that I only plot the region I'm interested in
- I plotted the "projected x-velocity field" (so the integral of v_x dz, really) in that region, with colour coding such that red = negative, blue = positive
- I used the same streamline annotations as before

![image](https://github.com/user-attachments/assets/544f24ed-6b36-4603-a34f-2f20b38ef1a0)

As we can see, the velocity along x neatly matches the streamlines.

Now, luckily, `yt` has a way of removing the "bulk velocity" from a region. In a given region (which could be `all_data` or a `sphere` as I did), you can define a field parameter called `bulk_velocity` to be, for example, the velocity of the halo of interest. Then, if you deposit the "relative" velocities on a grid, you get essentially `velocity - bulk_velocity`, which you can nicely plot. See below for an example.

![image](https://github.com/user-attachments/assets/c8632c6b-8759-4c70-a3cf-1920f2424575)

**Comment by blaizot** [comment]
Awesome !! Thanks ! Can you commit that into the tutorial ? 
🙏
